export const menuArray = [
  {
    name: "Pizza",
    ingredients: ["pepperoni", "mushrom", "mozarella"],
    image: "images/pizza.webp",
    altText: "pizza",
    price: 16,
    quantity: 1,
    isAdded: false,
    id: 0,
  },
  {
    name: "Burger",
    ingredients: ["beef", "cheese", "lettuce"],
    image: "images/burger.webp",
    altText: "burger",
    price: 12,
    quantity: 1,
    isAdded: false,
    id: 1,
  },
  {
    name: "Seekh Kebab",
    ingredients: ["minced lamb", "garam masala", "onion"],
    image: "images/seekh-kebab.webp",
    altText: "Seekh kebab",
    price: 18,
    quantity: 1,
    isAdded: false,
    id: 2,
  },
  {
    name: "Shawarma",
    ingredients: ["marinated chicken", "garlic sauce", "pickles"],
    image: "images/shawarma.webp",
    altText: "Shawarma wrap",
    price: 10,
    quantity: 1,
    isAdded: false,
    id: 3,
  },
  {
    name: "Mint Margarita",
    ingredients: ["fresh mint", "lime juice", "7up"],
    image: "images/mint-margarita.webp",
    altText: "Mint Margarita cocktail",
    price: 6,
    quantity: 1,
    isAdded: false,
    id: 4,
  },
  {
    name: "Coke",
    ingredients: ["sparkling water", "natural flavors", "sugar"],
    image: "images/coke.webp",
    altText: "Coke beverage",
    price: 5,
    quantity: 1,
    isAdded: false,
    id: 5,
  },
];
